#!/bin/bash
HERE=$(dirname $(readlink -f "${0}"))
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"
export PATH="$HERE/usr/sbin:$HERE/usr/bin:$HERE/sbin:$HERE/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HERE/lib:$HERE/usr/lib:$HERE/lib/x86_64-linux-gnu:$HERE/usr/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH="$HERE/usr/lib/x86_64-linux-gnu/mesa:$HERE/usr/lib/x86_64-linux-gnu/mesa-egl:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$HERE/lib/x86_64-linux-gnu:$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu:$HERE/usr/lib/x86_64-linux-gnu/mesa:$HERE/usr/lib/x86_64-linux-gnu/mesa-egl:$HERE/usr/lib/x86_64-linux-gnu/pulseaudio:$HERE/usr/lib/x86_64-linux-gnu/samba:$LD_LIBRARY_PATH
export export LD_LIBRARY_PATH="$HERE/usr/local/samba/bin/:/usr/local/samba/sbin/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HERE_LIBRARY_PATH:$LD_LIBRARY_PATH
export KODI_HOME="${HERE}"/usr/share/kodi/
export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/
"${HERE}"/usr/bin/kodi$@
